### ISSUE TITLE
FileNotFoundError on using cpp-header-checker

### ISSUE THREAD

**Issue by gtsc** [wqking/cpp-header-checker#2]
Hi - I really like the idea of the tool and want to use it for one of my projects, however, I struggle with doing so.
Hence, I went back to your example of using the tool on eventpp. In addition, I only executed it on one file, using the following command:
`python3 cpp-header-checker/cpp-header-checker.py complete --source "OWN_PATH_TO_EVENTPP/include/eventpp/eventqueue.h" --temp ./temp --command "gcc {file} -c -o {file}.o -IOWN_PATH_TO_EVENTPP/include" --exclude _i.h`
(ofc replacing the OWN_PATH_TO_EVENTPP)

However, doing so I get the following error:

> Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "cpp-header-checker/cpp-header-checker.py", line 216, in <lambda>
    thread = threading.Thread(target = lambda : self._executeThread())
  File "cpp-header-checker/cpp-header-checker.py", line 230, in _executeThread
    self._doTask(task)
  File "cpp-header-checker/cpp-header-checker.py", line 234, in _doTask
    self._processor.process(task)
  File "cpp-header-checker/cpp-header-checker.py", line 113, in process
    self.doProcess(header)
  File "cpp-header-checker/cpp-header-checker.py", line 127, in doProcess
    result = subprocess.run(command, stdout = subprocess.PIPE, stderr = subprocess.STDOUT, universal_newlines = True)
  File "/usr/lib/python3.8/subprocess.py", line 493, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1704, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'gcc ./temp/yuzbwfxflxtc_140022813349696_1648708701/maaelbyrhfjq_140022805473024_1648708701.cpp -c -o ./temp/yuzbwfxflxtc_140022813349696_1648708701/maaelbyrhfjq_140022805473024_1648708701.cpp.o -Ieventpp/include'

I checked some obvious things that could go wrong:
- I made sure that the `temp` directory exists
- I made sure that `gcc` is functional
- I checked with reduced number of arguments on call, but even with this call it happens: `python3 cpp-header-checker/cpp-header-checker.py complete --source "OWN_PATH_TO_EVENTPP/include/eventpp/eventqueue.h"`

My system is
- Ubuntu 20.04
- GCC 9.3.0
- Python 3.8.10

Any help on where I potentially go wrong?

**Comment by wqking** [comment]
Thanks for the bug report. I will test it on Ubuntu and see if anything wrong.

**Comment by wqking** [comment]
I've fixed the problem. The problem is caused by the different shell behavior on Linux and Windows.
Please check.

**Comment by gtsc** [comment]
Perfect, I got the code working on eventpp! Thanks for the swift help. I will try this tool now on my code base. Will report back, if anything won't work.
